name: Update

on:
  schedule:
    #- cron: '0 4,10,22 * * *'  # 每天的 GMT+8 时区的 6、12、18点的第0分钟执行
    - cron: '0 10 * * *'  # 每天的 GMT+8 时区的 12点 第0分钟 执行
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Install OpenCC
        run: pip install opencc-python-reimplemented
                
      - name: Run Updating...
        run: python ${{ github.workspace }}/capture.py

      - name: Submit Changed
        run: |
          git config --local user.email "killua1989@163.com"
          git config --local user.name "cdesign89"
          git add .
          git commit *.txt -m "Add generated file"
          #git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
